name: JS Actions

on: [push, release]

jobs:
  action:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: "call action"
        uses: ./
        with:
          myToken: ${{ github.token }}
